### ISSUE TITLE
Depends on Find::Lib which breaks while testing due to '.' missing in @INC

### ISSUE THREAD

**Issue by waterkip** [libwww-perl/WWW-Mechanize-Cached#17]
Due to a bug in Find::Lib WWW::Mechanize::Cached cannot be installed when running tests with Find::Lib: https://rt.cpan.org/Public/Bug/Display.html?id=120523

**Comment by oalders** [comment]
I'm sorry that I missed this.  Don't know why.  Do you remember how to reproduce this?

**Comment by oalders** [comment]
Actually, it looks like it's only being used in `t/cache_key.t`.  I think we can remove this module from the test.
