### ISSUE TITLE
Test error with LWP::UserAgent v 6.64

### ISSUE THREAD

**Issue by chylli-binary** [libwww-perl/WWW-Mechanize-Cached#27]
reproduce:
```
mkdir tmp
cd tmp
cpanm --reinstall -l local -n LWP::UserAgent@6.64
cpanm --reinstall -l local WWW::Mechanize::Cached
```

Test result:
```
t/006-cached-chi.t ........... ok
Can't store CODE items at /usr/lib/perl5/5.34/core_perl/Storable.pm line 370, at /home/chylli/.cpanm/work/1651414937.988007/WWW-Mechanize-Cached-1.55/blib/lib/WWW/Mechanize/Cached.pm line 130.

#   Failed test 'no exceptions'                                                                
#   at t/default.t line 16.                                                                    
#          got: 'Can't store CODE items at /usr/lib/perl5/5.34/core_perl/Storable.pm line 370, at /home/chylli/.cpanm/work/1651414937.988007/WWW-Mechanize-Cached-1.55/blib/lib/WWW/Mechanize/Cached.pm line 130.                                                                            
# '
#     expected: undef       
# Looks like you failed 1 test of 1.
```

**Comment by chylli-binary** [comment]
Started from LWP::UserAgent v6.63

**Comment by oalders** [comment]
Thanks @chylli-binary! This starts with the change to `LWP::UserAgent` where meta-refresh tags are now followed when `max_redirect > 0`. In the failing tests, the error goes away when we set `max_redirect => 0` when creating the mech object. However, if we then revert the change to allow redirects, the test begin passing again, so it looks like this is happening with that specific version of `LWP::UserAgent` when the cache has not yet been created.

First off, I think we need to be better about ensuring that the tests always use a cache in a random namespece and then we can look into what's causing this to happen. Normally redirects aren't being cached, but if the meta-refresh is coming from a page with a 2xx response code, then this module will assume it's ok to cache it.

**Comment by vanHoesel** [comment]
`HTTP::Status` provides a test `is_cacheable_by_default`, I propose to use that instead of assuming a `2xx` response is OK to cache... it is not!
